Option to save current tmux session as tmux-project

diff --git a/tmux-project b/tmux-project
--- a/tmux-project
+++ b/tmux-project
@@ -12,6 +12,7 @@ options:
   -h, --help       Display this help message
   -l, --list       List known tmux-projects
   -n, --new        Create a new tmux-project file
+  -s, --save       Save current session as tmux-project
   -v, --version    Display the version number
 
 EOF
@@ -54,6 +55,26 @@ list_projects() {
   exit 0
 }
 
+save_project() {
+  if [ -z "$TMUX" ]; then
+    echo "$SCRIPT_NAME: can't store current session if tmux isn't active"
+    exit 1
+  fi
+
+  PROJECT_NAME=$( tmux display-message -p '#S' )
+
+  if [[ -f "$PROJECT_DIR/$PROJECT_NAME" ]]; then
+    echo "$SCRIPT_NAME: '$PROJECT_NAME' already exists in $PROJECT_DIR"
+    exit 1
+  fi
+
+  touch "$PROJECT_DIR/$PROJECT_NAME"
+
+  echo "$SCRIPT_NAME: saved '$PROJECT_NAME'"
+
+  exit 0
+}
+
 # Transform long options to short options
 for arg in "$@"; do
   shift
@@ -67,6 +88,9 @@ for arg in "$@"; do
     "--new")
       set -- "$@" "-n"
       ;;
+    "--save")
+      set -- "$@" "-s"
+      ;;
     "--version")
       set -- "$@" "-v"
       ;;
@@ -77,7 +101,7 @@ for arg in "$@"; do
 done
 
 # Parse short options
-while getopts "hlnv" opt; do
+while getopts "hlnsv" opt; do
   case "$opt" in
     "h")
       usage
@@ -87,6 +111,9 @@ while getopts "hlnv" opt; do
       ;;
     "n")
       new_project $@
+      ;;
+    "s")
+      save_project
       ;;
     "v")
       version
